### ISSUE TITLE
spinner.error is not a function

### ISSUE THREAD

**Issue by fundon** [chenshuai2144/fetch-blocks#1]
感觉没经过测试呀

```
⠋ 🧐  find config.ts ...(node:59934) UnhandledPromiseRejectionWarning: TypeError: spinner.error is not a function
    at module.exports (/node_modules/fetch-blocks/src/fetch-blocks.js:176:13)
    at Object.<anonymous> (/node_modules/fetch-blocks/cli.js:28:1)
```

**Comment by fundon** [comment]
https://github.com/chenshuai2144/fetch-blocks/blob/master/src/fetch-blocks.js#L171

https://github.com/chenshuai2144/fetch-blocks/blob/master/src/fetch-blocks.js#L177
